title: Bharat Khanna
logo: /assets/img/logo.png
description: Data science leader with 15 years of expertise in financial and human capital analytics in the pharmaceutical, security, and financial industries
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
